//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.fru {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/WebService", ConfigurationName="fru.WebServicePruebaSoap")]
    public interface WebServicePruebaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Tipo_Producto_Sel_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Tipo_Producto_Sel_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Tipo_Medida_Sel_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Tipo_Medida_Sel_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Tipo_Cultivo_Sel_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Tipo_Cultivo_Sel_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Direccion_Ins", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Direccion_Ins(string nombre, int numero, int id_comuna, int coordenada_x, int coordenada_y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Usuario_Sel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Usuario_Sel(int rut, string pas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Usuario_Sel_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Usuario_Sel_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Productores_Hab_Sel_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Productores_Hab_Sel_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Productores_Hab_Sel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Productores_Hab_Sel(int rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Regiones_Sel_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Regiones_Sel_All();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Comunas_Sel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Comunas_Sel(int idregion, int idcomuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Usuario_Ins", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Usuario_Ins(int rut, string contrasena, int id_tipo_perfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Productor_Ins", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Productor_Ins(int rut, char dv, string nombre, string apellido, char sexo, int id_direccionparticular, int telefono, string correo, int id_direccionnegocio, int mismadireccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Clientes_Ins", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Clientes_Ins(int rut, char dv, string nombre, string apellido, char sexo, string correo, int telefono, int bloqueado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Usuarios_Perfiles_Ins", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Usuarios_Perfiles_Ins(int rut, int id_tipo_perfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebService/Cliente_Direcciones_Ins", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Cliente_Direcciones_Ins(int rut, int id_direccion, char primaria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePruebaSoapChannel : BLL.fru.WebServicePruebaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePruebaSoapClient : System.ServiceModel.ClientBase<BLL.fru.WebServicePruebaSoap>, BLL.fru.WebServicePruebaSoap {
        
        public WebServicePruebaSoapClient() {
        }
        
        public WebServicePruebaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePruebaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePruebaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePruebaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Tipo_Producto_Sel_All() {
            return base.Channel.Tipo_Producto_Sel_All();
        }
        
        public System.Data.DataSet Tipo_Medida_Sel_All() {
            return base.Channel.Tipo_Medida_Sel_All();
        }
        
        public System.Data.DataSet Tipo_Cultivo_Sel_All() {
            return base.Channel.Tipo_Cultivo_Sel_All();
        }
        
        public int Direccion_Ins(string nombre, int numero, int id_comuna, int coordenada_x, int coordenada_y) {
            return base.Channel.Direccion_Ins(nombre, numero, id_comuna, coordenada_x, coordenada_y);
        }
        
        public System.Data.DataSet Usuario_Sel(int rut, string pas) {
            return base.Channel.Usuario_Sel(rut, pas);
        }
        
        public System.Data.DataSet Usuario_Sel_All() {
            return base.Channel.Usuario_Sel_All();
        }
        
        public System.Data.DataSet Productores_Hab_Sel_All() {
            return base.Channel.Productores_Hab_Sel_All();
        }
        
        public System.Data.DataSet Productores_Hab_Sel(int rut) {
            return base.Channel.Productores_Hab_Sel(rut);
        }
        
        public System.Data.DataSet Regiones_Sel_All() {
            return base.Channel.Regiones_Sel_All();
        }
        
        public System.Data.DataSet Comunas_Sel(int idregion, int idcomuna) {
            return base.Channel.Comunas_Sel(idregion, idcomuna);
        }
        
        public void Usuario_Ins(int rut, string contrasena, int id_tipo_perfil) {
            base.Channel.Usuario_Ins(rut, contrasena, id_tipo_perfil);
        }
        
        public void Productor_Ins(int rut, char dv, string nombre, string apellido, char sexo, int id_direccionparticular, int telefono, string correo, int id_direccionnegocio, int mismadireccion) {
            base.Channel.Productor_Ins(rut, dv, nombre, apellido, sexo, id_direccionparticular, telefono, correo, id_direccionnegocio, mismadireccion);
        }
        
        public void Clientes_Ins(int rut, char dv, string nombre, string apellido, char sexo, string correo, int telefono, int bloqueado) {
            base.Channel.Clientes_Ins(rut, dv, nombre, apellido, sexo, correo, telefono, bloqueado);
        }
        
        public void Usuarios_Perfiles_Ins(int rut, int id_tipo_perfil) {
            base.Channel.Usuarios_Perfiles_Ins(rut, id_tipo_perfil);
        }
        
        public void Cliente_Direcciones_Ins(int rut, int id_direccion, char primaria) {
            base.Channel.Cliente_Direcciones_Ins(rut, id_direccion, primaria);
        }
    }
}
